/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IGreeter } from "../IGreeter";

export class IGreeter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGreeter {
    return new Contract(address, _abi, signerOrProvider) as IGreeter;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "greet",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
